#!/usr/bin/env node

/**
 * CiberCelia - Automated Content Builder
 * Scans content/posts, content/noticias, content/recursos, content/cursos, content/proyectos
 * and compiles the content manifest automatically.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(ROOT_DIR, 'content');
const ASSETS_JS_DIR = path.join(ROOT_DIR, 'assets', 'js');
const ASSETS_DATA_DIR = path.join(ROOT_DIR, 'assets', 'data');

// Helper to parse Markdown file frontmatter
function parseMarkdownFile(filePath, category) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  const relPath = path.relative(ROOT_DIR, filePath).replace(/\\/g, '/');
  const filename = path.basename(filePath, '.md');
  
  let metadata = {
    id: filename,
    title: filename,
    category: category,
    date: new Date().toISOString().split('T')[0],
    author: 'CiberCelia',
    author_github: 'cibercelia',
    tags: [],
    summary: '',
    file: relPath
  };

  let content = raw;

  if (raw.startsWith('---')) {
    const end = raw.indexOf('---', 3);
    if (end !== -1) {
      const frontmatter = raw.slice(3, end).trim();
      content = raw.slice(end + 3).trim();

      frontmatter.split('\n').forEach(line => {
        const colonIdx = line.indexOf(':');
        if (colonIdx !== -1) {
          const key = line.slice(0, colonIdx).trim();
          let val = line.slice(colonIdx + 1).trim();
          
          if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
            val = val.slice(1, -1);
          } else if (val.startsWith('[') && val.endsWith(']')) {
            try {
              val = JSON.parse(val.replace(/'/g, '"'));
            } catch (e) {
              val = val.slice(1, -1).split(',').map(s => s.trim().replace(/['"]/g, ''));
            }
          }
          metadata[key] = val;
        }
      });
    }
  }

  // Calculate estimated reading time (~200 words/min)
  const words = content.split(/\s+/).filter(Boolean).length;
  metadata.readingTime = `${Math.max(1, Math.ceil(words / 200))} min`;
  metadata.content = content;

  return metadata;
}

// Helper to scan directory for Markdown files
function scanMarkdownDir(dirName, category) {
  const dirPath = path.join(CONTENT_DIR, dirName);
  if (!fs.existsSync(dirPath)) return [];

  const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.md'));
  return files.map(file => parseMarkdownFile(path.join(dirPath, file), category))
    .sort((a, b) => (b.date || '').localeCompare(a.date || ''));
}

// Helper to load JSON datasets
function loadJsonDataset(filename) {
  const filePath = path.join(CONTENT_DIR, filename);
  if (!fs.existsSync(filePath)) return [];
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (err) {
    console.error(`Error loading ${filename}:`, err);
    return [];
  }
}

function build() {
  console.log('🔨 Compilando contenidos de CiberCelia...');

  const posts = scanMarkdownDir('posts', 'post');
  const noticias = scanMarkdownDir('noticias', 'noticia');
  const recursos = loadJsonDataset(path.join('recursos', 'index.json'));
  const cursos = loadJsonDataset(path.join('cursos', 'index.json'));
  const proyectos = loadJsonDataset(path.join('proyectos', 'index.json'));

  const manifest = {
    posts,
    noticias,
    recursos,
    cursos,
    proyectos
  };

  if (!fs.existsSync(ASSETS_DATA_DIR)) {
    fs.mkdirSync(ASSETS_DATA_DIR, { recursive: true });
  }

  // Write compiled JSON
  const jsonPath = path.join(ASSETS_DATA_DIR, 'content.json');
  fs.writeFileSync(jsonPath, JSON.stringify(manifest, null, 2), 'utf-8');
  console.log(`✅ Generado: ${path.relative(ROOT_DIR, jsonPath)}`);

  // Generate assets/js/content.js
  const jsContent = `/**
 * CiberCelia - Content Manifest & Markdown Engine
 * Auto-generated by scripts/build.js
 */

const CIBERCELIA_CONTENT = ${JSON.stringify(manifest, null, 2)};

// Markdown Parser Engine using marked.js with GFM & custom callouts
const MarkdownEngine = {
  // Strip frontmatter if present
  stripFrontmatter(md) {
    if (md.startsWith('---')) {
      const end = md.indexOf('---', 3);
      if (end !== -1) {
        return md.slice(end + 3).trim();
      }
    }
    return md;
  },

  // Parse Markdown to HTML
  render(md) {
    let raw = this.stripFrontmatter(md);

    // Process GitHub Callouts / Alerts (> [!NOTE], > [!IMPORTANT], > [!WARNING], > [!TIP], > [!CAUTION])
    raw = raw.replace(/^>\\s*\\[!(NOTE|IMPORTANT|WARNING|TIP|CAUTION)\\]\\s*\\n((?:>.*\\n?)*)/gim, (match, type, content) => {
      const cleanContent = content.replace(/^>\\s?/gm, '').trim();
      const typeLower = type.toLowerCase();
      const titles = {
        note: 'Nota',
        important: 'Importante',
        warning: 'Advertencia',
        tip: 'Consejo',
        caution: 'Precaución'
      };
      const innerHtml = typeof marked !== 'undefined' ? marked.parse(cleanContent) : cleanContent;
      return \`<div class="callout callout-\${typeLower}">
        <div class="callout-title"><strong>\${titles[typeLower] || type}</strong></div>
        <div class="callout-body">\${innerHtml}</div>
      </div>\\n\\n\`;
    });

    let html = '';
    if (typeof marked !== 'undefined') {
      marked.setOptions({
        gfm: true,
        breaks: false
      });
      html = marked.parse(raw);
    } else {
      html = raw;
    }

    // Enhance code blocks with copy button
    html = html.replace(/<pre><code class="language-([\\w-]+)">([\\s\\S]*?)<\\/code><\\/pre>/g, (match, lang, code) => {
      return \`<div class="code-wrapper" style="position: relative;">
        <button class="code-copy-btn" onclick="copyCodeSnippet(this)">Copiar</button>
        <pre class="language-\${lang}"><code class="language-\${lang}">\${code}</code></pre>
      </div>\`;
    });

    html = html.replace(/<pre><code>([\\s\\S]*?)<\\/code><\\/pre>/g, (match, code) => {
      return \`<div class="code-wrapper" style="position: relative;">
        <button class="code-copy-btn" onclick="copyCodeSnippet(this)">Copiar</button>
        <pre class="language-text"><code class="language-text">\${code}</code></pre>
      </div>\`;
    });

    return html;
  }
};

// Global helper for code snippet copy
window.copyCodeSnippet = function(btn) {
  const pre = btn.parentElement ? btn.parentElement.querySelector('pre code') : null;
  const code = pre ? pre.innerText : (btn.nextElementSibling ? btn.nextElementSibling.innerText : '');
  navigator.clipboard.writeText(code).then(() => {
    const originalText = btn.innerText;
    btn.innerText = '¡Copiado!';
    btn.style.borderColor = '#10b981';
    btn.style.color = '#10b981';
    setTimeout(() => {
      btn.innerText = originalText;
      btn.style.borderColor = '';
      btn.style.color = '';
    }, 2000);
  });
};
`;

  const jsPath = path.join(ASSETS_JS_DIR, 'content.js');
  fs.writeFileSync(jsPath, jsContent, 'utf-8');
  console.log(`✅ Generado: ${path.relative(ROOT_DIR, jsPath)}`);
  console.log(`📊 Total compilado: ${posts.length} posts, ${noticias.length} noticias, ${recursos.length} recursos, ${cursos.length} cursos, ${proyectos.length} proyectos.`);
}

build();
